### ISSUE TITLE
Create PubID gem for ETSI documents ("pubid-etsi")

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-etsi#1]
I've uploaded the list of ETSI PubIDs to the repo.

## Anatomy of an ETSI PubID

"ETSI EN 300 058-3 V1.2.4 (1998-06)"

* Type: "EN"
* Major number: "300"
* Minor number: "058"
* Part: "3"
* Version: "V1.2.4" or Edition ("ed. 1")
* Date: "1998-06"

## Number

e.g.
* 136 521-1
* 137 320
* ZSM 009-1
* ORI 002-2
* NFV-IFA 052
* NFV 006
* mWT 018
* F5G 016
* ECI 001-5-2
* 203 915-4-5
* 100 392-3-15

## Document types

* EN "European Standard"
* ES "ETSI Standard"
* EG "ETSI Guide"
* TS "Technical Specification"
* (deprecated) ETR "European telecommunications report"
* (deprecated) ETS "European telecommunications standard"
* (deprecated) I-ETS: Provisional ETS
* TBR "Technical Basis for Regulation"
* (deprecated) TCRTR "Technical Committee Report - Technical Report"
* (deprecated) NET "Norme Européenne de Télécommunication" / "Technical
* GR "Group Report"
* GS "Group Specification"
* SR "Special Report"

There are also Amendments and Corrigenda:
* ETSI ETS 300 102-1/A2 ed.1 (1993-10)
* ETSI ETS 300 102-1/A1 ed.1 (1993-04)
* ETSI ETS 300 055-1/C2 ed.1 (1996-01)
* ETSI ETS 300 055-1/C1 ed.1 (1994-04)

```sh
$ cat etsi-pubids.txt | cut -d ' ' -f 2 | sort | uniq
EG
EN
ES
ETR
ETS
GR
GS
GTS
I-ETS
NET
SR
TBR
TCRTR
TR
TS
```

## Version / Edition

```
V3.23.1
ed.1
ed.2
ed.3
ed.7
```

## Publication date

```
(1990-08)
(1990-12)
(1991-02)
(1992-09)
...
(2021-09)
(2023-09)
(2023-10)
```

## Data

[etsi-pubids.txt.zip](https://github.com/relaton/relaton/files/13211843/etsi-pubids.txt.zip)

**Comment by mico** [comment]
@ronaldtse what is identifiers like `ETSI GTS GSM 02.01 V5.5.0 (1999-08)`? Seems like it's something special.

**Comment by ronaldtse** [comment]
@mico seems like it.

## Analysis of the "GTS GSM" document identifier

In the official documents, they are called in a pattern of "ETSI GSM 02.01 (ETS 300 500)".

"GTS" means "GSM Technical Specification".

<img width="795" alt="Screenshot 2023-11-08 at 2 14 23 PM" src="https://github.com/metanorma/pubid-etsi/assets/11865/6bd33da4-33ea-4c6e-9f86-e29609a69ae3">

From the relationship between:
<img width="785" alt="Screenshot 2023-11-08 at 2 35 46 PM" src="https://github.com/metanorma/pubid-etsi/assets/11865/71bdf0c4-9bd9-495e-b5e1-145938de4c52">

```
ETSI GTS GSM 01.04 V5.0.0 (1996-03)
...
ETSI ETR 100 ed.3 (1995-04)
```

i.e.
* "ETSI GTS GSM 01.04 V5.0.0 (1996-03)" is newer than "ETSI ETR 100 ed.3 (1995-04)"

=> So "ETSI GSM 02.01 (ETS 300 500)" means that "ETSI GSM 02.01" supersedes "ETSI ETS 300 500".

## Availability of identifiers

In the data set, it contains both identifiers but for different editions/versions:
```
ETSI ETS 300 500 ed.2 (1996-01)
...
ETSI GTS GSM 02.01 V5.5.0 (1999-08)
```

I think this means:
* it is hard to connect the relationship between the "ETSI GTS" document and the "ETSI ETS" document.


## Correct representation of "GTS GSM" vs "GSM"

Also there are these pairs:
```
ETSI GTS GSM 01.04 V5.0.0 (1996-03)
ETSI GTS 01.04 V3.0.1 (1991-02)
```

Clearly they are the same document but different editions, but the previous of "GTS" vs "GTS GSM" are different.

I believe technically they should all just be called "ETSI GSM xx.yy":

<img width="836" alt="Screenshot 2023-11-08 at 2 43 41 PM" src="https://github.com/metanorma/pubid-etsi/assets/11865/eaf76d96-90a0-4a67-8310-3e7c5ab6697a">

<img width="814" alt="Screenshot 2023-11-08 at 2 45 12 PM" src="https://github.com/metanorma/pubid-etsi/assets/11865/bfa206ba-f6c1-4194-aa93-f371866814f7">

<img width="617" alt="Screenshot 2023-11-08 at 2 44 18 PM" src="https://github.com/metanorma/pubid-etsi/assets/11865/527725a8-55c6-4377-aba3-3390e4feb528">

<img width="767" alt="Screenshot 2023-11-08 at 2 44 29 PM" src="https://github.com/metanorma/pubid-etsi/assets/11865/0a24de4c-51bf-473a-b6da-e892c8eadfca">
